---
title: 'Henry Holmes'
timezone: EST
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@henryholmes.design
description: Henry is a product designer and movement artist based in New York City.
baseurl: ''
url: 'http://henryholmes.design'
twitter_username: syntactile
github_username: hholmes
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
exclude:
- frasco.config.js
- Gemfile
- Gemfile.lock
- gulp_tasks
- gulpfile.js
- LICENSE
- node_modules
- npm-debug.log
- package.json
- package-lock.json
- README.md
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- yarn.lock
