---
title: 'Frasco: Jekyll Starter Project'
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@domain.com
description: Quick starter project for Jekyll including full setup for gulp, Sass,
  Autoprefixer, Bourbon/Neat/Bitters, Browserify, imagemin, Browsersync, PostCSS etc.
baseurl: ''
url: ''
twitter_username: ixkaito
github_username: ixkaito
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-seo-tag
exclude:
- frasco.config.js
- Gemfile
- Gemfile.lock
- gulp_tasks
- gulpfile.js
- LICENSE
- node_modules
- npm-debug.log
- package.json
- package-lock.json
- README.md
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- yarn.lock
