backend:
  name: github
  repo: hholmes/henryholmes.design
  branch: staging # Branch to update (optional; defaults to master)
  auth_endpoint: auth

media_library:
  name: uploadcare
  config:
    publicKey: 6e0aed1d8c0dcc0424c4
    
media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
  - label: "Meta"
    name: "meta"
    files: 
      - label: "Header"
        name: "header"
        file: "content/meta/header.json"
        format: "json"
        fields:
          - {label: "logo", name: "logo", widget: image}
          - label: "Pages"
            name: "pages"
            widget: "relation"
            collection: "pages"
            searchFields: ["title"]
            valueField: "title"
            multiple: true
          - label: "Projects"
            name: "projects"
            widget: "relation"
            collection: "project"
            searchFields: ["title"]
            valueField: "title"
            multiple: true
      - label: "Intro"
        name: "intro"
        file: "content/meta/intro.json"
        format: "json"
        fields:
          - {label: Body, name: body, widget: markdown, required: true}
      - label: "Social"
        name: "social"
        file: "content/meta/social.json"
        format: "json"
        fields:
          - {label: Facebook, name: facebook, widget: string, required: false}
          - {label: Twitter, name: twitter, widget: string, required: false}
          - {label: GitHub, name: github, widget: string, required: false}
          - {label: Instagram, name: instagram, widget: string, required: false}
          - {label: LinkedIn, name: linkedin, widget: string, required: false}
  - label: "Project"
    name: "project"
    folder: "content/project"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Type, name: type, widget: string, required: true}
      - {label: Subtitle, name: subtitle, widget: string, required: false}
      - {label: CoverImage, name: cover, widget: image, required: false}
      - label: Sections
        name: "sections"
        widget: list
        required: false
        fields:
          - {label: Body, name: body, widget: markdown, required: false}
          - label: "Topic"
            name: "topic"
            widget: "relation"
            collection: "topic"
            searchFields: ["title"]
            valueField: "title"
            required: false
  - label: "Article"
    name: "article"
    folder: "content/article"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Description, name: description, widget: string, required: true}
      - {label: Call to Action, name: cta, widget: string, required: true}
      - {label: CoverImage, name: cover, widget: image, required: false}
      - label: Sections
        name: "sections"
        widget: list
        required: false
        fields:
          - {label: Body, name: body, widget: markdown, required: false}
          - label: "Topic"
            name: "topic"
            widget: "relation"
            collection: "topic"
            searchFields: ["title"]
            valueField: "title"
  - label: "Topic"
    name: "topic"
    folder: "content/topic"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Abbr, name: abbr, widget: string, required: true}
      - {label: Description, name: description, widget: text, required: false}
  # - label: "Resume"
  #   name: "resume"
  #   file: "content/resume.json"
  #   format: "json"
  #   fields:
  #     - label: "Companies"
  #       name: "companies"
  #       widget: list
  #       required: true
  #       fields:
  #         - {label: Title, name: title, widget: string, required: true}
  #         - {label: Logo, name: logo, widget: image, required: false}
  #         - {label: Acronym, name: acronym, widget: string, required: false}
  - label: "Pages"
    name: "pages"
    folder: "content/page"
    create: true
    format: "json"
    slug: "{{title}}"
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Body, name: body, widget: markdown}