backend:
  name: git-gateway
  repo: http://github.com/hholmes/henryholmes.design
  branch: master # Branch to update (optional; defaults to master)
  accept_roles: #optional - accepts all users if left out
    - admin
  site_domain: https://henryholmes.design/#/

media_library:
  name: uploadcare
  config:
    publicKey: 6e0aed1d8c0dcc0424c4
media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Projects"
    name: "projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Subtitle, name: subtitle, widget: string, required: false}
      - {label: CoverImage, name: cover, widget: image, required: false}
      - label: Sections
        name: "sections"
        widget: list
        required: false
        fields:
          - {label: Body, name: body, widget: markdown, required: false}
          - label: "Topic"
            name: "topics"
            widget: "relation"
            collection: "topics"
            searchFields: ["title"]
            valueField: "title"
  - label: "Topics"
    name: "topics"
    folder: "content/topics"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Abbr, name: abbr, widget: string, required: true}
      - {label: Description, name: description, widget: text, required: false}
  - label: "Pages"
    name: "pages"
    files:
      - label: "About"
        name: "about"
        file: "content/about.json"
        fields:
          - {label: Title, name: title, widget: string, required: true}
          - {label: Body, name: body, widget: text}
      - label: "CV"
        name: "cv"
        file: "content/cv.json"
        fields:
          - {label: Title, name: title, widget: string, required: true}
          - {label: Body, name: body, widget: text}