backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  accept_roles: #optional - accepts all users if left out
    - admin

media_library:
  name: uploadcare
  config:
    publicKey: 6e0aed1d8c0dcc0424c4
media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "Project"
    name: "project"
    folder: "content/project"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Subtitle, name: subtitle, widget: string, required: false}
      - {label: CoverImage, name: cover, widget: image, required: false}
      - label: Sections
        name: "sections"
        widget: list
        required: false
        fields:
          - {label: Body, name: body, widget: markdown, required: false}
          - label: "Topic"
            name: "topic"
            widget: "relation"
            collection: "topic"
            searchFields: ["title"]
            valueField: "title"
  - label: "Topic"
    name: "topic"
    folder: "content/topic"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Abbr, name: abbr, widget: string, required: true}
      - {label: Description, name: description, widget: text, required: false}
  - label: "Pages"
    name: "pages"
    folder: "content/page"
    fields:
      - {label: Title, name: title, widget: string, required: true}
      - {label: Body, name: body, widget: markdown}